### ISSUE TITLE
Composer-File broken

### ISSUE THREAD

**Issue by tronet-dev** [OXID-eSales/developer_documentation#1]
When trying to install oxid via composer as explained [here](http://oxid-eshop-developer-documentation.readthedocs.io/en/latest/getting_started/resources/ce/composer.html), the **core**-folder is missing for some reason. This leads to having problems with the access-rights and you can't continue the installation-routine.

If you follow this instruction however, everything works fine. 
[working example](https://github.com/OXID-eSales/oxideshop_ce/)

**Comment by MantasVaitkunas** [comment]
Hi @tronet-dev, thanks for issue report.
Problem was with satis server, it generated eShop package without directories which were described in .gitignore file. There is an issue report https://github.com/composer/satis/issues/204
We already working on removing trailing slashes from .gitignore file, to fix existing issue.

BTW: `core` directory should be only in composer vendor directory, as it is autoloaded with composer autloader.

**Comment by MantasVaitkunas** [comment]
I reverted some changes from .gitignore. Also tried to install OXID eShop, everything looks fine now. Closing an issue.
