### ISSUE TITLE
Images for documentation

### ISSUE THREAD

**Issue by gregorhyneck** [OXID-eSales/developer_documentation#11]
Please store images here instead of inside the repository in order to keep the disk space low for this repository.

![edit-article-link-mediagallery](https://user-images.githubusercontent.com/12152978/33273789-9fb0ea74-d38e-11e7-83bc-6055b045219b.png)
![mediagallery-no-files](https://user-images.githubusercontent.com/12152978/33273797-a403966c-d38e-11e7-9819-3c21e4d0e142.png)
![mediagallery-with-files](https://user-images.githubusercontent.com/12152978/33273799-a60d13e8-d38e-11e7-9345-8d077794c20a.png)

**Comment by gregorhyneck** [comment]
No Images needed at the moment.

**Comment by Sieg** [comment]
Even if they will be needed, maybe they could go to closed issue.
