### ISSUE TITLE
Document how to use settings in metadata.php

### ISSUE THREAD

**Issue by alfredbez** [OXID-eSales/developer_documentation#2]
Document how to define settings in metadata.php after [this](https://github.com/OXID-eSales/oxideshop_ce/pull/381) is merged.

**Comment by stasiukaitis-saulius** [comment]
Hi @alfredbez,

I add a links to your pull requests. They might be useful as an example.
https://github.com/OXID-eSales/developer_documentation/commit/e437ad5a2baeaa9c4ae985469edc5aa3af15e9d1

We have a task in an OXID backlog to improve documentation for themes handling, but it's not on the top priority list. 

If you have any ideas how to improve the document feel free to contribute with a pull request ;)

**Comment by stasiukaitis-saulius** [comment]
Hi,

I hope this chapter is enough to close this issue 
https://github.com/OXID-eSales/developer_documentation/tree/b-6.0/modules/skeleton/metadataphp
